program project03

    ! goal: calculus of SUM from -inf to +inf of sin(x)/x
    ! but since we can't ask a computer to calculate infinite, let's ask the
    ! user to set an intervall : [intervall_inf ; intervall_sup]
    ! /!\ [abandoned for now: see further (1)] the user will also be asked to choose a pace : 1, 0.1, 0.01...
    ! 0 is a critical point where exists an indetermined form of 0/0
    ! we'll avoid breaking the code by assigning the value at x=0 whereas the
    ! rest of the values will be automatically generated by the computer calculating sin(x)/x

    implicit none

    integer(8) :: x, intervall_inf, intervall_sup
    real(8) :: x_real,y, summ

    ! /!\ loops must be integers, we can not ask for reals
    ! (1) idea : with the pace argument we could ask what decimal we want
    ! and then just make a bigger scale for the intervall : 1 to 10 would be
    ! 0.01 to 0.10 
    ! real(8) :: x,y,summ, pace, intervall_inf, intervall_sup

    ! /!\ discovered a new error: intent(in) is for functions not programs
    ! real(8), intent(in) :: pace, intervall_inf, intervall_sup

    ! input of the intervall

    print *, "select starting x for the sum"
    read *, intervall_inf

    print *, "select ending x for the sum"
    read *, intervall_sup

    print *, "the intervall you chose is:", intervall_inf, ";", intervall_sup

    ! /!\ abandoned feature for now, see (1)
    ! input of the pace
    ! print *, "Please choose the pace : 1.0, 0.1, 0.01, 0.001..."
    ! read *, pace

    ! (1-b)feature: if the values entered are not numeric...
    ! here i'd like to create an if statement that checks whether pace,
    ! intervall_inf & intervall_sup are real or integer
    ! if TRUE or TRUE then we run the code
    ! and if it's integers we make them reals(8)

    ! (2) same idea but staying with integers for now as (1) will probably not
    ! be developed

    ! else... the values entered are not numeric we print a message error and the
    ! program is finished, but we didn't run the code risking error
    
    ! ============================================================================

    ! for now let's ignore this security step and assume the values are properly
    ! entered

    summ = 0.0

    ! if we ever enter pace as a parameter:
    ! do x=intervall_inf,intervall_sup,pace

    ! for now...
    do x=intervall_inf,intervall_sup

        ! we have a problem: because of the loop, x is an integer, but we'd get:
        ! Error: 'x' argument of 'sin' intrinsic at (1) must be REAL or COMPLEX

        ! so let's create a 'second','mirror' x (because we can't modify the inital one
        ! since it's used for the loop and needs to remain an integer) which is
        ! a real(8) : x_real

        x_real = real(x)

        if (x .ne. 0) then
    
            ! remember: we don't want the computer to try and calculate sin(x)/x
            ! for x = 0 so here is how we protect the code

            y = (sin(x_real)/x_real)
            summ = summ + y

        else

            ! here x = 0, so we need to determine the value of sin(x)/x with
            ! another method
            ! let's use Taylor's method
            ! which says : sin(x)/x when x -> 0 = 1 - (x^2)/3! + (x^4)/5! - (x^6)/7! + o(x^6)
            ! with o(x^6) -> 0 when x -> 0
            ! and let's just ignore the o(x^6)

            ! /!\ I was having trouble using the fact(n) function so I just
            ! typed the values of 3!, 5!, and 7! but I'm interested in knowing
            ! how to properly use n! on fortran
            ! Error: Function 'fact' at (1) has no IMPLICIT type
            ! y = 1 - (x_real**2)/fact(3) + (x_real**4)/fact(5) - (x_real**6)/fact(7)

            y = 1 - (x_real**2)/6 + (x_real**4)/120 - (x_real**6)/5040
            summ = summ + y

        end if

    end do

    print *, "Final sum: ", summ

end program project03
